---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by samin.
--- DateTime: 25/11/2022 14:05
---
local maps = require 'maps'
local tables = require 'common.tables'

local MapInterpreter = {}
MapInterpreter.__index = MapInterpreter

-- Waypoint follower map character to allowed-actions
function MapInterpreter:waypointInterpreter(waypoint)
    local indexToWaypoints = {
        ["1"] = { 'N', 'E' },
        ["2"] = { 'N', 'W' },
        ["3"] = { 'N', 'S' },
        ["4"] = { 'S', 'E' },
        ["5"] = { 'S', 'W' },
        ["6"] = { 'E', 'W' },
        ["B"] = { 'N', 'E', 'S', 'W' },
        ["E"] = { 'E' },
        ["W"] = { 'W' },
        ["N"] = { 'N' },
        ["S"] = { 'S' }
    }
    return indexToWaypoints[waypoint]
end

function MapInterpreter:TriggerInterpreter(waypoint)
    local indexToTrigger= {
        ["1"] = "intersection",
        ["2"] = "lane"
    }
    return indexToTrigger[waypoint]
end

function MapInterpreter:ExtractWaypoint(position, imgWidth)
    local map = maps["logic"].layout
    local map_coordinate = self:CoordinateTranslation(position, imgWidth)
    local waypoint =map:sub(map_coordinate, map_coordinate)
    return waypoint
end

function MapInterpreter:ExtractTrigger(position, imgWidth)
    local map = maps["trigger"].layout
    local map_coordinate = self:CoordinateTranslation(position, imgWidth)
    local trigger =map:sub(map_coordinate, map_coordinate)
    return trigger
end

function MapInterpreter:CoordinateTranslation(position, imgWidth)
    local map_coordinate = (position[2] * (imgWidth + 1)) + position[1] + 1
    return map_coordinate
end

return MapInterpreter